# 1) Import Data
* Import Dependencies
* Import CSV

### Import Dependencies

In [1]:
import pandas as pd
import numpy as np
from geopy.distance import geodesic
from mapping import MILITARY_BASES

### Import CSV

In [2]:
data_raw = pd.read_csv("aircraft_data_new.csv")

# Convert 'timestamp' column to datetime
data_raw["datetime"] = pd.to_datetime(data_raw["datetime"])

# Sort by hex and then datetime
data_raw = data_raw.sort_values(by=["hex", "datetime"]).reset_index(drop=True)

print("Unique hex codes: ", data_raw['hex'].nunique())
print("Unique callsigns: ", data_raw['callsign'].nunique())
data_raw.head(10)

Unique hex codes:  12
Unique callsigns:  12

,hex,callsign,datetime,operator,tail number,squawk,altitude,latitude,longitude,type,heading,ground speed
0,ae07f8,TEDDY45,2025-05-25 13:45:24.738465,Usaf | 437aw [kchs],97-0046,1501,6150,41.664431,-73.540140,C-17A Globemaster,331.0,247.0
1,ae07f8,TEDDY45,2025-05-25 13:46:42.116406,Usaf | 437aw [kchs],97-0046,1501,5850,41.744182,-73.587190,C-17A Globemaster,334.0,232.0
2,ae07f8,TEDDY45,2025-05-25 13:47:42.872921,Usaf | 437aw [kchs],97-0046,2645,5150,41.761644,-73.651096,C-17A Globemaster,242.0,216.0
3,ae07f8,TEDDY45,2025-05-25 13:48:43.475530,Usaf | 437aw [kchs],97-0046,2645,4750,41.699014,-73.715586,C-17A Globemaster,242.0,289.0
4,ae07f8,TEDDY45,2025-05-25 13:49:44.114103,Usaf | 437aw [kchs],97-0046,2645,3875,41.658669,-73.784490,C-17A Globemaster,230.0,223.0
5,ae07f8,TEDDY45,2025-05-25 13:50:44.483272,Usaf | 437aw [kchs],97-0046,2645,3875,41.595026,-73.827341,C-17A Globemaster,190.0,272.0
6,ae07f8,TEDDY45,2025-05-25 13:51:45.148663,Usaf | 437aw [kchs],97-0046,2645,3125,41.555510,-73.851350,C-17A Globemaster,205.0,253.0
7,ae07f8,TEDDY45,2025-05-25 13:52:46.009656,Usaf | 437aw [kchs],97-0046,2645,2375,41.543893,-73.899800,C-17A Globemaster,276.0,202.0
8,ae07f8,TEDDY45,2025-05-25 13:54:47.022342,Usaf | 437aw [kchs],97-0046,2645,1525,41.557054,-73.988529,C-17A Globemaster,213.0,215.0
9,ae080e,RCH808,2025-05-25 13:45:24.738456,United States Air Force,99-0168,0750,20850,35.141797,-79.702955,C-17A Globemaster,27.0,432.0

# 2) Transform Data
* Base Metrics

### Base Metrics

In [3]:
max_distance_miles = 15

def find_nearest_base(row):
  """
  Checks if a given lat/lon is within max_distance_miles of any base.
  If so, keep track of the base that is the closet and add that info.
  """
  benchmark = max_distance_miles
  row['near base'] = None
  row['distance to base'] = None
  point = (row['latitude'], row['longitude'])
  if row['altitude'] <= 10000:
    for base_name, coords in MILITARY_BASES.items():
      base_point = (coords['lat'], coords['lon'])
      distance = geodesic(point, base_point).miles
      if distance <= benchmark:
        # This distance becomes the benchmark
        benchmark = distance
        row['near base'] = base_name
        row['distance to base'] = int(distance)
  return row

# --- Apply the function to your DataFrame ---
df = data_raw.apply(lambda row: find_nearest_base(row), axis=1)

df.head()

,hex,callsign,datetime,operator,tail number,squawk,altitude,latitude,longitude,type,heading,ground speed,near base,distance to base
0,ae07f8,TEDDY45,2025-05-25 13:45:24.738465,Usaf | 437aw [kchs],97-0046,1501,6150,41.664431,-73.540140,C-17A Globemaster,331.0,247.0,None,NaN
1,ae07f8,TEDDY45,2025-05-25 13:46:42.116406,Usaf | 437aw [kchs],97-0046,1501,5850,41.744182,-73.587190,C-17A Globemaster,334.0,232.0,None,NaN
2,ae07f8,TEDDY45,2025-05-25 13:47:42.872921,Usaf | 437aw [kchs],97-0046,2645,5150,41.761644,-73.651096,C-17A Globemaster,242.0,216.0,None,NaN
3,ae07f8,TEDDY45,2025-05-25 13:48:43.475530,Usaf | 437aw [kchs],97-0046,2645,4750,41.699014,-73.715586,C-17A Globemaster,242.0,289.0,None,NaN
4,ae07f8,TEDDY45,2025-05-25 13:49:44.114103,Usaf | 437aw [kchs],97-0046,2645,3875,41.658669,-73.784490,C-17A Globemaster,230.0,223.0,None,NaN

In [4]:
test = df[~df['near base'].isna()]

test.head(50)

,hex,callsign,datetime,operator,tail number,squawk,altitude,latitude,longitude,type,heading,ground speed,near base,distance to base
6,ae07f8,TEDDY45,2025-05-25 13:51:45.148663,Usaf | 437aw [kchs],97-0046,2645,3125,41.555510,-73.851350,C-17A Globemaster,205.0,253.0,Stewart ANGB,13.0
7,ae07f8,TEDDY45,2025-05-25 13:52:46.009656,Usaf | 437aw [kchs],97-0046,2645,2375,41.543893,-73.899800,C-17A Globemaster,276.0,202.0,Stewart ANGB,10.0
8,ae07f8,TEDDY45,2025-05-25 13:54:47.022342,Usaf | 437aw [kchs],97-0046,2645,1525,41.557054,-73.988529,C-17A Globemaster,213.0,215.0,Stewart ANGB,6.0
282,ae117d,RCH406,2025-05-25 16:18:18.642410,United States Air Force,02-1111,6115,2875,27.865225,-82.741426,C-17A Globemaster,175.0,272.0,MacDill AFB,13.0
283,ae117d,RCH406,2025-05-25 16:19:19.285434,United States Air Force,02-1111,6115,2200,27.798128,-82.733008,C-17A Globemaster,172.0,260.0,MacDill AFB,13.0
284,ae117d,RCH406,2025-05-25 16:20:19.640257,United States Air Force,02-1111,6115,1475,27.776555,-82.657906,C-17A Globemaster,74.0,307.0,MacDill AFB,9.0
285,ae117d,RCH406,2025-05-25 16:21:20.055590,United States Air Force,02-1111,6115,1475,27.793981,-82.572975,C-17A Globemaster,56.0,273.0,MacDill AFB,4.0
286,ae117d,RCH406,2025-05-25 16:22:20.876624,United States Air Force,02-1111,6115,1500,27.850454,-82.519073,C-17A Globemaster,41.0,250.0,MacDill AFB,0.0
287,ae117d,RCH406,2025-05-25 16:23:21.532647,United States Air Force,02-1111,6115,1500,27.821163,-82.499511,C-17A Globemaster,227.0,215.0,MacDill AFB,2.0
288,ae117d,RCH406,2025-05-25 16:24:21.917337,United States Air Force,02-1111,6115,1500,27.785597,-82.531955,C-17A Globemaster,213.0,170.0,MacDill AFB,4.0
289,ae117d,RCH406,2025-05-25 16:25:22.834628,United States Air Force,02-1111,6115,1125,27.806354,-82.561154,C-17A Globemaster,6.0,189.0,MacDill AFB,3.0
290,ae117d,RCH406,2025-05-25 16:26:23.529063,United States Air Force,02-1111,6115,125,27.830417,-82.539836,C-17A Globemaster,50.0,141.0,MacDill AFB,1.0
354,ae123a,RCH857,2025-05-25 13:53:46.660806,United States Air Force,04-4128,2673,3075,39.913221,-74.583982,C-17A Globemaster,166.0,281.0,JB McGuire-Dix-Lakehurst,9.0
355,ae123a,RCH857,2025-05-25 13:54:47.022335,United States Air Force,04-4128,2673,4050,39.838464,-74.557101,C-17A Globemaster,164.0,276.0,JB McGuire-Dix-Lakehurst,14.0
368,ae123a,RCH857,2025-05-25 14:07:55.506848,United States Air Force,04-4128,2673,1900,39.056954,-75.203308,C-17A Globemaster,232.0,268.0,Dover AFB,14.0
369,ae123a,RCH857,2025-05-25 14:08:56.123929,United States Air Force,04-4128,2673,1800,39.022128,-75.239160,C-17A Globemaster,199.0,263.0,Dover AFB,13.0
370,ae123a,RCH857,2025-05-25 14:09:56.685213,United States Air Force,04-4128,2673,1825,39.030168,-75.299107,C-17A Globemaster,305.0,172.0,Dover AFB,10.0
371,ae123a,RCH857,2025-05-25 14:10:57.365165,United States Air Force,04-4128,2673,1775,39.061306,-75.348604,C-17A Globemaster,325.0,239.0,Dover AFB,7.0
372,ae123a,RCH857,2025-05-25 14:11:58.179751,United States Air Force,04-4128,2673,1100,39.069195,-75.359502,C-17A Globemaster,328.0,226.0,Dover AFB,6.0
373,ae123a,RCH857,2025-05-25 16:54:43.521584,United States Air Force,04-4128,5653,2500,39.214801,-75.478356,C-17A Globemaster,NaN,NaN,Dover AFB,6.0
374,ae123a,RCH857,2025-05-25 16:55:44.138450,United States Air Force,04-4128,5653,4525,39.216631,-75.366362,C-17A Globemaster,80.0,216.0,Dover AFB,8.0
375,ae123a,RCH857,2025-05-25 16:56:44.356599,United States Air Force,04-4128,5653,6625,39.185838,-75.252812,C-17A Globemaster,104.0,317.0,Dover AFB,11.0
430,ae123f,IROC61,2025-05-25 14:59:11.005620,Usaf | 305amw | 6as [kwri],04-4134,1434,1875,39.855838,-74.616943,C-17A Globemaster,354.0,170.0,JB McGuire-Dix-Lakehurst,13.0
431,ae123f,IROC61,2025-05-25 15:00:11.373567,Usaf | 305amw | 6as [kwri],04-4134,1434,1850,39.901459,-74.616516,C-17A Globemaster,2.0,162.0,JB McGuire-Dix-Lakehurst,10.0
432,ae123f,IROC61,2025-05-25 15:01:12.277678,Usaf | 305amw | 6as [kwri],04-4134,1434,1750,39.942192,-74.596544,C-17A Globemaster,19.0,146.0,JB McGuire-Dix-Lakehurst,7.0
433,ae123f,IROC61,2025-05-25 15:02:13.115169,Usaf | 305amw | 6as [kwri],04-4134,1434,650,39.977665,-74.594484,C-17A Globemaster,350.0,121.0,JB McGuire-Dix-Lakehurst,4.0
434,ae123f,IROC61,2025-05-25 15:03:13.927493,Usaf | 305amw | 6as [kwri],04-4134,1434,800,40.007462,-74.599792,C-17A Globemaster,352.0,120.0,JB McGuire-Dix-Lakehurst,2.0
447,ae1463,RCH3243,2025-05-25 16:59:46.118766,United States Air Force,06-6165,2161,1200,39.145569,-75.486344,C-17A Globemaster,340.0,154.0,Dover AFB,2.0
448,ae1463,RCH3243,2025-05-25 17:00:46.471953,United States Air Force,06-6165,2161,2900,39.203705,-75.508317,C-17A Globemaster,348.0,254.0,Dover AFB,6.0
449,ae1463,RCH3243,2025-05-25 17:01:47.078523,United States Air Force,06-6165,2161,6675,39.273743,-75.525274,C-17A Globemaster,351.0,266.0,Dover AFB,10.0